# Generated by Django 5.0.7 on 2024-07-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wilaya_product_stock_alter_product_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wilaya',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('machinery', 'Machinery'), ('grain', 'Grain'), ('property', 'Property'), ('others', 'Others')], default='others', max_length=255),
        ),
    ]
